# Generated by Django 4.2.3 on 2023-07-12 03:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormularioEncuesta",
            fields=[
                (
                    "id",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
                ("ci", models.CharField(max_length=150)),
                ("photo_ci_front", models.URLField(blank=True, null=True)),
                ("photo_ci_back", models.URLField(blank=True, null=True)),
                (
                    "photo_person",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(blank=True, null=True), size=None
                    ),
                ),
                (
                    "photo_form",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(blank=True, null=True), size=None
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulario Encuesta",
                "verbose_name_plural": "Formulario Encuesta",
                "ordering": ("id",),
            },
        ),
        migrations.AlterField(
            model_name="comunidad",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunidades",
                to="core.municipio",
            ),
        ),
    ]
