# Generated by Django 4.2.3 on 2023-07-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_photo_alter_formularioencuesta_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formularioencuesta",
            name="photo_form",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formularioencuesta",
            name="photo_person",
            field=models.TextField(blank=True, null=True),
        ),
    ]
