# Generated by Django 4.2.3 on 2023-07-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_formularioencuesta_photo_form_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoForm",
            fields=[
                (
                    "id",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.formularioencuesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo Encuesta",
                "verbose_name_plural": "Photos Encuestas",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PhotoPerson",
            fields=[
                (
                    "id",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.formularioencuesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo Persona",
                "verbose_name_plural": "Photos Persona",
                "ordering": ("id",),
            },
        ),
        migrations.DeleteModel(name="Photo",),
    ]
