# Generated by Django 4.2.3 on 2023-07-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_photoform_photoperson_delete_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="formularioencuesta",
            name="latitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formularioencuesta",
            name="longitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
