# Generated by Django 4.2.3 on 2023-07-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_formularioencuesta_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunidad",
            name="id",
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="comunidad",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="formularioencuesta",
            name="ci",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="formularioencuesta",
            name="id",
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="formularioencuesta",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="id",
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="photoform",
            name="id",
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="photoperson",
            name="id",
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
