# Generated by Django 4.2.3 on 2023-07-12 06:34

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_comunidad_id_alter_comunidad_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formularioencuesta",
            name="photo_ci_back",
            field=core.models.URLFieldExtended(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="formularioencuesta",
            name="photo_ci_front",
            field=core.models.URLFieldExtended(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="photoform",
            name="url",
            field=core.models.URLFieldExtended(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="photoperson",
            name="url",
            field=core.models.URLFieldExtended(blank=True, max_length=500, null=True),
        ),
    ]
