# Generated by Django 4.2.3 on 2023-07-12 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_formulariopiquete_photoestructura_photocampo"),
    ]

    operations = [
        migrations.AddField(
            model_name="formularioencuesta",
            name="comunidad",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.comunidad",
            ),
            preserve_default=False,
        ),
    ]
